[package]
name = "random_sampling"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8"
clap = { version = "4.4", features = ["derive"] }


[dev-dependencies]
random_sampling = { path = "." }